Default: &defaults
  database: dota-counterpick.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: dota-counterpick_test.sqlite3
  <<: *defaults

Staging:
  database: dota-counterpick_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: dota-counterpick_production.sqlite3
  poolsize: 100
  <<: *defaults
